import {
  Box,
  Button,
  Card,
  CardBody,
  CardHeader,
  Text,
  Divider,
  FormControl,
  FormHelperText,
  FormLabel,
  Heading,
  Input,
  SimpleGrid,
  Stack,
  Link,
  Tooltip,
  InputGroup,
  InputRightAddon,
  useToast,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import chainlinkPriceFeed from "@/artifacts/@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol/AggregatorV3Interface.json";
import challengeFactory from "@/artifacts/contracts/ChallengeFactory.sol/ChallengeFactory.json";
import {
  useContractRead,
  useContractWrite,
  usePrepareContractWrite,
} from "wagmi";
import ContractInfo from "@/components/create-a-challenge/ContractInfo";
import { CHALLENGE_FACTORY_ADDRESS } from "@/artifacts/contracts/challengeFactoryAddress";
import { BigNumber, ethers, utils } from "ethers";
import ChallengeCreator from "@/components/create-a-challenge/ChallengeCreator";
import {
  useAggregatorV3InterfaceLatestRoundData,
  useChallengeFactoryGetFactoryDetails,
  useChallengeGetChallengeDetails,
} from "@/generated";
import {
  ChallengeDetails,
  ChallengeFactoryDetails,
} from "@/components/create-a-challenge/types";
import { EthPriceFeedDetails } from "../components/create-a-challenge/types";

export default function CreateChallenge() {
  //* State and env variables

  const ethPriceFeedAddress =
    process.env.NEXT_PUBLIC_CHAINLINK_ETHUSD_CONTRACT_ADDRESS || "";

  //* Contract info state
  const [ethPriceFeedDetails, setEthPriceFeedDetails] =
    useState<EthPriceFeedDetails>({ ethPriceFeedAddress: ethPriceFeedAddress });

  const [challengeFactoryDetails, setChallengeFactoryDetails] =
    useState<ChallengeFactoryDetails>({
      challengeFactoryAddress: CHALLENGE_FACTORY_ADDRESS,
    });

  const [challengeDetails, setChallengeDetails] = useState<ChallengeDetails>({
    challengeAddress: "",
  });

  //* Wagmi autogenerated hook for eth price feed
  const { refetch: refetchEthFeed } = useAggregatorV3InterfaceLatestRoundData({
    // @ts-expect-error
    address: ethPriceFeedAddress,
    enabled: false,
    onSuccess: (data) => {
      console.log("ETH/USD Price Feed Data: ", data);
      setEthPriceFeedDetails({
        ...ethPriceFeedDetails,
        ethPriceFeedAddress: ethPriceFeedAddress,
        ethUsdPrice: data?.answer || 0,
        lastUpdatedAt: data?.updatedAt || 0,
        refetchEthFeed: refetchEthFeed,
      });
    },
  });

  //* Wagmi autogenerated hook for challenge factory
  const { refetch: refetchChallengeFactory } =
    useChallengeFactoryGetFactoryDetails({
      address: CHALLENGE_FACTORY_ADDRESS,
      enabled: false,
      onSuccess: (data) => {
        console.log("Challenge Factory Data: ", data);

        setChallengeFactoryDetails({
          ...challengeFactoryDetails,
          owner: data?._owner || ethers.constants.AddressZero,
          startBlock: data?._startBlock || 0,
          minEntryFee: data?._minEntryFee || 0,
          minChallengeDuration: data?._minChallengeDuration || 0,
          maxChallengeDuration: data?._maxChallengeDuration || 0,
          minLockDuration: data?._minLockDuration || 0,
          maxLockDuration: data?._maxLockDuration || 0,
          settlementDuration: data?._settlementDuration || 0,
          challengeImplementation: data?._challengeImplementation || "",
          refetchChallengeFactory: refetchChallengeFactory,
        });
      },
    });

  //* Wagmi autogenerated hook for challenge details
  const { refetch: refetchChallengeDetails } = useChallengeGetChallengeDetails({
    // @ts-expect-error
    address: challengeDetails?.challengeAddress,
    enabled: false,
    onSuccess: (data) => {
      console.log("Challenge Details called: ", data);
      setChallengeDetails({
        ...challengeDetails,
        owner: data?._owner || ethers.constants.AddressZero,
        startBlock: data?._startBlock || 0,
        startTime: data?._startTime || 0,
        entryFee: data?._entryFee || 0,
        lockTime: data?._lockTime || 0,
        settlementStartTime: data?._settlementStartTime || 0,
        settlementEndTime: data?._settlementEndTime || 0,
        creator: data?._creator || ethers.constants.AddressZero,
        creatorPrediction: data?._creatorPrediction || 0,
        challenger: data?._challenger || ethers.constants.AddressZero,
        challengerPrediction: data?._challengerPrediction || 0,
        settled: data?._settled || false,
        settledBy: data?._settledBy || ethers.constants.AddressZero,
        active: data?._active || false,
        winner: data?._winner || ethers.constants.AddressZero,
        settlementFeePercent: data?._SETTLEMENT_FEE_PERCENT || 0,
        settlementFeeMax: data?._SETTLEMENT_FEE_MAX || 0,
        refetchChallengeDetails: refetchChallengeDetails,
      });
    },
    onError: (error) => {
      console.log("Error fetching challenge details: ", error);
    },
  });

  useEffect(() => {
    refetchEthFeed();
    refetchChallengeFactory();
    if (challengeDetails?.challengeAddress) refetchChallengeDetails();
    console.log("UE called");
  }, [
    refetchEthFeed,
    refetchChallengeFactory,
    refetchChallengeDetails,
    challengeDetails?.challengeAddress,
  ]);

  return (
    <Box bg="secondary.100" p={10} minHeight="90vh">
      <SimpleGrid
        height="100%"
        spacing={4}
        templateColumns={{ sm: "1fr", md: "1fr 1fr" }}
      >
        <ContractInfo
          ethPriceFeedDetails={ethPriceFeedDetails}
          challengeFactoryDetails={challengeFactoryDetails}
          challengeDetails={challengeDetails}
          setChallengeDetails={setChallengeDetails}
        />
        <ChallengeCreator
          challengeFactoryDetails={challengeFactoryDetails}
          challengeDetails={challengeDetails}
          setChallengeDetails={setChallengeDetails}
        />
      </SimpleGrid>
    </Box>
  );
}
